MFixedPoint: mn::MFixedPoint Namespace Reference
mn::MFixedPoint Namespace Reference
Namespaces
detail
Classes
class Fp32f
class Fp32s
The template argument p in all of the following functions refers to the fixed point precision (e.g. p = 8 gives 24.8 fixed point functions). Contains mathematical operator overloading. Doesn't have modulus (%) overloading.
class Fp64f
64-bit fixed-point library.
class Fp64s
Fixed-point, 64-bit, slow (slower than Fp64f), but more powerful, library.
class Port
Functions
int32_t fixrsqrt16 (int32_t a)
static int32_t fast_div16 (int32_t a, int32_t b)
int32_t fixsqrt16 (int32_t a)
Calculates squareroot.
template<uint8_t q>
int32_t FixMulF (int32_t a, int32_t b)
Perform a fixed point multiplication without a 64-bit intermediate result.
template<uint8_t q>
int32_t FixMul (int32_t a, int32_t b)
Perform a fixed point multiplication using a 64-bit intermediate result to prevent intermediary overflow problems.
template<uint8_t q>
int32_t fixdiv (int32_t a, int32_t b)
template<uint8_t q>
int32_t fixinv (int32_t a)
template<uint8_t q>
int32_t FloatToRawFix32 (float f)
Converts from float to a raw fixed-point number.
template<uint8_t q>
int32_t DoubleToRawFix32 (double f)
Converts from double to a raw fixed-point number.
int32_t fixcos16 (int32_t a)
int32_t fixsin16 (int32_t a)
template<uint8_t q>
Fp32f< q > operator+ (int32_t a, Fp32f< q > b)
template<uint8_t q>
Fp32f< q > operator- (int32_t a, Fp32f< q > b)
template<uint8_t q>
Fp32f< q > operator* (int32_t a, Fp32f< q > b)
template<uint8_t q>
Fp32f< q > operator/ (int32_t a, Fp32f< q > b)
template<uint8_t q>
Fp32f< q > sin (Fp32f< q > a)
template<uint8_t q>
Fp32f< q > cos (Fp32f< q > a)
template<uint8_t q>
Fp32f< q > sqrt (Fp32f< q > a)
template<uint8_t q>
Fp32f< q > rsqrt (Fp32f< q > a)
template<uint8_t q>
Fp32f< q > inv (Fp32f< q > a)
template<uint8_t q>
Fp32f< q > abs (Fp32f< q > a)
template<>
Fp32f< 16 > sin (Fp32f< 16 > a)
template<>
Fp32f< 16 > cos (Fp32f< 16 > a)
template<>
Fp32f< 16 > sqrt (Fp32f< 16 > a)
template<>
Fp32f< 16 > rsqrt (Fp32f< 16 > a)
template<>
Fp32f< 16 > inv (Fp32f< 16 > a)
template<uint8_t q>
Fp32f< q > multiply_accumulate (int32_t count, const Fp32f< q > *a, const Fp32f< q > *b)
template<uint8_t p>
int64_t FixMulF (int64_t a, int64_t b)
Perform a fixed point multiplication without a 128-bit intermediate result.
template<uint8_t p>
int64_t FixDiv (int64_t a, int64_t b)
Perform a fixed point division without a 128-bit intermediate result.
template<uint8_t p>
int64_t FloatToRawFix64 (float f)
Converts from float to a raw fixed-point number.
template<uint8_t p>
int64_t DoubleToRawFix64 (double f)
Converts from float to a raw fixed-point number.
Function Documentation
abs()
template<uint8_t q> Fp32f<q> mn::MFixedPoint::abs (Fp32f< q > a) inline
Definition at line 543 of file Fp32f.hpp.
References mn::MFixedPoint::Fp32f< q >::rawVal.
cos() [1/2]
template<uint8_t q> Fp32f<q> mn::MFixedPoint::cos (Fp32f< q > a) inline
Referenced by operator/().
cos() [2/2]
template<> Fp32f<16> mn::MFixedPoint::cos (Fp32f< 16 > a) inline
Definition at line 561 of file Fp32f.hpp.
References fixcos16(), and mn::MFixedPoint::Fp32f< q >::rawVal.
DoubleToRawFix32()
template<uint8_t q> int32_t mn::MFixedPoint::DoubleToRawFix32 (double f)
Converts from double to a raw fixed-point number.
Do not write "myFpNum = FloatToRawFix32()"! This function outputs a raw number, so you would have to use the syntax "myFpNum.rawVal = FloatToRawFix32()".
Warning
Slow!
Definition at line 194 of file Fp32f.hpp.
References fixcos16(), fixrsqrt16(), fixsin16(), and fixsqrt16().
DoubleToRawFix64()
template<uint8_t p> int64_t mn::MFixedPoint::DoubleToRawFix64 (double f)
Converts from float to a raw fixed-point number.
Do not write "myFpNum = DoubleToRawFix64()"! This function outputs a raw number, so you would have to use the syntax "myFpNum.rawVal = DoubleToRawFix64()".
Warning
Slow!
Definition at line 63 of file Fp64f.hpp.
fast_div16()
static int32_t mn::MFixedPoint::fast_div16 (int32_t a, int32_t b) inline static
Definition at line 107 of file Fp32f.cpp.
Referenced by fixsqrt16().
fixcos16()
int32_t mn::MFixedPoint::fixcos16 (int32_t a)
Referenced by cos(), and DoubleToRawFix32().
FixDiv()
template<uint8_t p> int64_t mn::MFixedPoint::FixDiv (int64_t a, int64_t b) inline
Perform a fixed point division without a 128-bit intermediate result.
No loss of precision since shift is done before division.
Warning
This is fast but beware of intermediary overflow!
Definition at line 41 of file Fp64f.hpp.
fixdiv()
template<uint8_t q> int32_t mn::MFixedPoint::fixdiv (int32_t a, int32_t b) inline
Definition at line 88 of file Fp32f.hpp.
fixinv()
template<uint8_t q> int32_t mn::MFixedPoint::fixinv (int32_t a) inline
Definition at line 145 of file Fp32f.hpp.
References mn::MFixedPoint::detail::CountLeadingZeros(), and FixMul().
FixMul()
template<uint8_t q> int32_t mn::MFixedPoint::FixMul (int32_t a, int32_t b) inline
Perform a fixed point multiplication using a 64-bit intermediate result to prevent intermediary overflow problems.
Note
Slower than Fp32f::FixMulF()
Definition at line 81 of file Fp32f.hpp.
Referenced by fixinv().
FixMulF() [1/2]
template<uint8_t p> int64_t mn::MFixedPoint::FixMulF (int64_t a, int64_t b) inline
Perform a fixed point multiplication without a 128-bit intermediate result.
Warning
This is fast but beware of intermediary overflow!
Definition at line 30 of file Fp64f.hpp.
FixMulF() [2/2]
template<uint8_t q> int32_t mn::MFixedPoint::FixMulF (int32_t a, int32_t b) inline
Perform a fixed point multiplication without a 64-bit intermediate result.
Note
This is fast but beware of intermediary overflow!
Definition at line 72 of file Fp32f.hpp.
fixrsqrt16()
int32_t mn::MFixedPoint::fixrsqrt16 (int32_t a)
Definition at line 73 of file Fp32f.cpp.
References mn::MFixedPoint::detail::CountLeadingZeros().
Referenced by DoubleToRawFix32(), and rsqrt().
fixsin16()
int32_t mn::MFixedPoint::fixsin16 (int32_t a)
Referenced by DoubleToRawFix32(), and sin().
fixsqrt16()
int32_t mn::MFixedPoint::fixsqrt16 (int32_t a)
Calculates squareroot.
Definition at line 117 of file Fp32f.cpp.
References fast_div16().
Referenced by DoubleToRawFix32(), and sqrt().
FloatToRawFix32()
template<uint8_t q> int32_t mn::MFixedPoint::FloatToRawFix32 (float f)
Converts from float to a raw fixed-point number.
Do not write "myFpNum = FloatToRawFix32()"! This function outputs a raw number, so you would have to use the syntax "myFpNum.rawVal = FloatToRawFix32()".
Warning
Slow!
Definition at line 184 of file Fp32f.hpp.
FloatToRawFix64()
template<uint8_t p> int64_t mn::MFixedPoint::FloatToRawFix64 (float f)
Converts from float to a raw fixed-point number.
Do not write "myFpNum = FloatToRawFix64()"! This function outputs a raw number, so you would have to use the syntax "myFpNum.rawVal = FloatToRawFix64()".
Warning
Slow!
Definition at line 53 of file Fp64f.hpp.
inv() [1/2]
template<uint8_t q> Fp32f<q> mn::MFixedPoint::inv (Fp32f< q > a) inline
Referenced by operator/().
inv() [2/2]
template<> Fp32f<16> mn::MFixedPoint::inv (Fp32f< 16 > a) inline
Definition at line 586 of file Fp32f.hpp.
References mn::MFixedPoint::Fp32f< q >::rawVal.
multiply_accumulate()
template<uint8_t q> Fp32f<q> mn::MFixedPoint::multiply_accumulate (int32_t count, const Fp32f< q > * a, const Fp32f< q > * b) inline
Definition at line 595 of file Fp32f.hpp.
References mn::MFixedPoint::Fp32f< q >::rawVal.
operator*()
template<uint8_t q> Fp32f<q> mn::MFixedPoint::operator* (int32_t a, Fp32f< q > b) inline
Note
Assumes integer has the same precision as Fp32f
Definition at line 513 of file Fp32f.hpp.
operator+()
template<uint8_t q> Fp32f<q> mn::MFixedPoint::operator+ (int32_t a, Fp32f< q > b) inline
Note
Assumes integer has the same precision as Fp32f
Definition at line 499 of file Fp32f.hpp.
operator-()
template<uint8_t q> Fp32f<q> mn::MFixedPoint::operator- (int32_t a, Fp32f< q > b) inline
Note
Assumes integer has the same precision as Fp32f
Definition at line 506 of file Fp32f.hpp.
operator/()
template<uint8_t q> Fp32f<q> mn::MFixedPoint::operator/ (int32_t a, Fp32f< q > b) inline
Definition at line 517 of file Fp32f.hpp.
References cos(), inv(), rsqrt(), sin(), and sqrt().
rsqrt() [1/2]
template<uint8_t q> Fp32f<q> mn::MFixedPoint::rsqrt (Fp32f< q > a) inline
Referenced by operator/().
rsqrt() [2/2]
template<> Fp32f<16> mn::MFixedPoint::rsqrt (Fp32f< 16 > a) inline
Definition at line 578 of file Fp32f.hpp.
References fixrsqrt16(), and mn::MFixedPoint::Fp32f< q >::rawVal.
sin() [1/2]
template<uint8_t q> Fp32f<q> mn::MFixedPoint::sin (Fp32f< q > a) inline
Referenced by operator/().
sin() [2/2]
template<> Fp32f<16> mn::MFixedPoint::sin (Fp32f< 16 > a) inline
Definition at line 553 of file Fp32f.hpp.
References fixsin16(), and mn::MFixedPoint::Fp32f< q >::rawVal.
sqrt() [1/2]
template<uint8_t q> Fp32f<q> mn::MFixedPoint::sqrt (Fp32f< q > a) inline
Referenced by operator/().
sqrt() [2/2]
template<> Fp32f<16> mn::MFixedPoint::sqrt (Fp32f< 16 > a) inline
Definition at line 570 of file Fp32f.hpp.
References fixsqrt16(), and mn::MFixedPoint::Fp32f< q >::rawVal.